### ISSUE TITLE
安装报‘devtool’错误，自己安装依赖运行又报错

### ISSUE THREAD

**Issue by MiaolwArea** [SidKwok/react-webpack-boilerplate#24]
安装完项目后报错，自己手动安装依赖运行npm run dev;又报错：These dependencies were not found: 后面一堆webpack-hot-middleware、react-hot-loader、react-dom相关的错误，而且里面默认package.json的dependencies默认没有react-router？！
现在运行不起来呀，急急

**Comment by SidKwok** [comment]
```
# install sao first
npm install -g sao

# download the template
sao SidKwok/react-webpack-boilerplate new-project --install

# if you would like to try React 16
sao SidKwok/react-webpack-boilerplate#next new-project --install

# install all this dependencies.
cd new-project
npm install
```

有按照这个步骤来吗？

**Comment by MiaolwArea** [comment]
感谢回复, 我又重试了一遍 还是一样的
```
? Project name new-project
? Project description A React project
? Author lwmiao
? Install react-router? Yes
? Pick the version of router v4
? Pick the type of router html5
? Install redux? Yes
? Pick the type of DevTools Browser
? Use ESLint to lint your code? No
? Unit test with jest? No

  To get started:

  cd new-project
  npm install
  npm run dev
ERROR TypeError: Cannot read property 'devtools' of undefined
    at post (/Users/MLW/.sao/repos/SidKwok-react-webpack-boilerplate/sao.js:122:20)
    at copy.then.stream (/usr/local/lib/node_modules/.sao_npminstall/sao/0.20.1/sao/lib/generate.js:217:34)
```
这里报错，目录结构生成了，然后我`cnpm i`安装依赖以后，`cnpm run dev`,就报错了....
```
MlwArea:new-project Area$ cnpm run dev

> new-project@1.0.0 dev /Users/MLW/Documents/Practice/new-project
> node build/dev-server



 ERROR  Failed to compile with **194** errors                               16:28:09

These dependencies were not found:

* strip-ansi in ./~/.npminstall/webpack-hot-middleware/2.18.2/webpack-hot-middleware/client.js?noInfo=true&reload=true
* ansi-html in ./~/.npminstall/webpack-hot-middleware/2.18.2/webpack-hot-middleware/client-overlay.js
...(省略)...
```

**Comment by SidKwok** [comment]
提供一下node和npm的版本号

**Comment by MiaolwArea** [comment]
node v7.6.0
npm 4.1.2

**Comment by SidKwok** [comment]
如果你很急的话，你可以先尝试使用[full-feature 分支](https://github.com/SidKwok/react-webpack-boilerplate/tree/full-features)下的东西：
```bash
git clone https://github.com/SidKwok/react-webpack-boilerplate.git

cd react-webpack-boilerplate

git checkout -b new-project origin/full-feature

cnpm install

npm run dev

```

**Comment by MiaolwArea** [comment]
貌似 也一样 我再找找原因

**Comment by SidKwok** [comment]
应该是node的问题，你可以尝试重新安装sao，如果不行的话，试试重新安装node
