### ISSUE TITLE
创建项目出错

### ISSUE THREAD

**Issue by ChiaJune** [SidKwok/react-webpack-boilerplate#28]
## 命令

``` bash
sao SidKwok/react-webpack-boilerplate new-project --install
```

## sao版本

v0.21.5

## 错误信息

``` bash
error Error: Path contains invalid characters: C:\Users\xxxx\.sao\repos\SidKwok::react-webpack-boilerplate\template
    at checkPath (C:\Users\xxxx\AppData\Roaming\npm\node_modules\sao\node_modules\make-dir\index.js:18:16)
    at Promise.resolve.then (C:\Users\xxxx\AppData\Roaming\npm\node_modules\sao\node_modules\make-dir\index.js:26:2)
```

**Comment by SidKwok** [comment]
用的是windows系统吗？

**Comment by ChiaJune** [comment]
嗯

**Comment by SidKwok** [comment]
#26

**Comment by ChiaJune** [comment]
ok!那我关issue了
