### ISSUE TITLE
创建项目带有条件判断

### ISSUE THREAD

**Issue by ChiaJune** [SidKwok/react-webpack-boilerplate#30]
下载的最新的项目，使用命令初始化的项目带有 **模板判断** 的代码，如下（以`.babelrc`为例，`package.json`也是，其他的还没看）：
``` javascript
{
    "presets": [
        ["env", {"modules": false}],
        "stage-1",
        "react"
    ],
    "comments": false,
    "plugins": [
        "transform-runtime",
        "transform-decorators-legacy"
    ],
    "env": {
        "production": {
            "plugins": [[
                "transform-react-remove-prop-types",
                {
                    "removeImport": true,
                    "ignoreFilenames": ["node_modules"]
                }
            ]]
        },
        "development": {
            "plugins": ["react-hot-loader/babel"]
        }{{#unit}},
        "test": {
            "presets": ["env", "stage-1"],
            "plugins": [
                ["module-resolver", {
                    "alias": {
                        "src": "./src"
                    }
                }]
            ]
        }{{/unit}}
    }
}
```

**Comment by SidKwok** [comment]
提供一下操作步骤，node版本，操作系统。

**Comment by ChiaJune** [comment]
步骤：
1. 下载最新的sao
2. 执行那一长串命令，install项目

node版本:6.11.1
操作系统: mac OSX10.12.6

**Comment by SidKwok** [comment]
我这边复现不了啊，你可以尝试把根目录下的.sao文件清除掉，然后重新执行相关命令。如果你项目比较急，你可以使用full-features分支下的文件。

**Comment by ChiaJune** [comment]
我在公司用的电脑是win10系统，不知道从什么时候开始一直报这个错误：

``` bash
error Error: Path contains invalid characters: C:\Users\xxx\.sao\repos\SidKwok::react-webpack-boilerplate\template
    at checkPath (C:\Users\xxx\AppData\Roaming\npm\node_modules\sao\node_modules\make-dir\index.js:18:16)
    at Promise.resolve.then (C:\Users\xxx\AppData\Roaming\npm\node_modules\sao\node_modules\make-dir\index.js:26:2)
```

项目构建不了，跟 #26 #28 是一样的错误。

关于复现的问题，我只有晚上回去用mac试一下。
我的项目不急。一直在关注你的这个项目，最近在从vue转到react，还在不断学习。给你点个赞:thumbsup::thumbsup::thumbsup:

**Comment by SidKwok** [comment]
首先谢谢你的支持~

这个是一个已知的bug，win10下会出现文件名出错的问题，感觉是sao那边的问题。但是由于一直没有办法搞到win10的电脑，而且最近项目比较忙，所以一直没有办法修复这里的问题，估计得搁置一阵子。但是你可以直接克隆full-feature里的文件，full-feature分支下的项目是直接可用的，直接`npm install`就可以用了，里面包含所有的特性。

**Comment by SidKwok** [comment]
如果你感兴趣preact的话，还可以关注一下preact分支，这个分支和主项目的配置一样，只是将react换成了preact，而且同样支持组件、redux的热更新，文件尺寸方面减少了大约百分之70，欢迎使用并提issue。

**Comment by ChiaJune** [comment]
## 操作系统
Mac OSX10.12.6
## Node & NPM & Yarn 版本
v6.11.1 & 3.10.10 & 0.27.5
## sao版本
v0.21.9

刚才重新下载`sao`，删除了`.sao/`目录，同时执行了`npm cache clean`和`yarn cache clean`
然后执行命令：
``` bash
sao SidKwok/react-webpack-boilerplate new-project --install
```
依然是这样的。

## 生成项目的代码（截取部分）

package.json
``` json
{
  "name": "{{ name }}",
  "version": "1.0.0",
  "description": "{{ description }}",
  "main": "src/main.js",
  "keywords": [
    "express",
    "webpack",
    "node",
    "spa"
  ],
  "author": "{{ author }}",
  "license": "MIT",
  "scripts": {
    "dev": "node build/dev-server",
    "build": "node build/build.js"{{#lint}},
    "lint": "eslint --ext .js,.jsx src{{#unit}} test{{/unit}}"{{/lint}}{{#unit}},
    "test": "jest"{{/unit}}
  },
...
}
```
.babelrc

``` json
{
    "presets": [
        ["env", {"modules": false}],
        "stage-1",
        "react"
    ],
    "comments": false,
    "plugins": [
        "transform-runtime",
        "transform-decorators-legacy"
    ],
    "env": {
        "production": {
            "plugins": [[
                "transform-react-remove-prop-types",
                {
                    "removeImport": true,
                    "ignoreFilenames": ["node_modules"]
                }
            ]]
        },
        "development": {
            "plugins": ["react-hot-loader/babel"]
        }{{#unit}},
        "test": {
            "presets": ["env", "stage-1"],
            "plugins": [
                ["module-resolver", {
                    "alias": {
                        "src": "./src"
                    }
                }]
            ]
        }{{/unit}}
    }
}
```

routes.js

``` javascript
import MainView from 'views/MainView'
import SyncView from 'views/SyncView'
{{#if_eq routerVersion "v4"~}}
import Loadable from 'react-loadable'
{{/if_eq}}

export default [
  {
    path: '/',
    component: MainView,
    childRoutes: [
      {
        path: '/sync',
        component: SyncView
      },
      {
        path: '/async',
        {{#if_eq routerVersion "v3"}}
        getComponent (nextState, cb) {
          (async () => {
            const view = await import('views/AsyncView')
            cb(null, view.default)
          })()
        }
        {{/if_eq}}
        {{#if_eq routerVersion "v4"}}
        component: Loadable({
          loader: () => import(`views/AsyncView`),
          // if you have your own loading component,
          // you should consider add it here
          loading: () => null
        })
        {{/if_eq}}
      }
    ]
  }
]
```

**Comment by SidKwok** [comment]
我今天用了sao 0.21.9 版本也遇到了这个问题，然后更新到0.22.1之后这个问题就没了，要不你试试？
